### PR TITLE
Use Ower handling from controller-runtime for Account 

### LINKED ISSUE #349: Owner Handling for Account
Currently, we use our own `OwnerReference` in Account controller, but since Account is cluster-scoped, we can use `controllerutil.SetControllerReference()` to handle that

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:
Since Account is cluster-scoped object, we can use `controllerutil.SetOwnerReference` and offload garbage collection to Kubernetes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #349 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nmiculinic** [comment]
I'm against this PR, since it includes additional work on the Account --> an object we're going to replace in the bulward integration.

**Comment by jiachengxu** [comment]
> I'm against this PR, since it includes additional work on the Account --> an object we're going to replace in the bulward integration.

Well, this is not a valid reason for me, since bulward integration will take some time, and we even don't have a proposal for that yet. I don't see anything/workload that introduced by this PR

**Comment by thetechnick** [comment]
This is actually not working (if I get the PR right):

Account -> Namespace **works**
Account -> Role/RoleBinding/Tenant **Does not work***

Reason:

>Note:
>Cross-namespace owner references are disallowed by design. This means:
>
>Namespace-scoped dependents can only specify owners in the same namespace, and owners that are cluster-scoped.
>Cluster-scoped dependents can only specify cluster-scoped owners, but not namespace-scoped owners.
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

*It works until GC ruins your day...

**Comment by thetechnick** [comment]
/unhold

Never mind this should work out fine

**Pull request merged**
