### PR TITLE
use kubermatic-labs/boilerplate

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
The boilerplate checker from the Kubermatic template project is not maintainable if it's spread across many different repositories. To remedy this we decided to turn it into a tiny standalone repository in https://github.com/kubermatic-labs/boilerplate and maintain it there.

This PR removes the old implementation and instead uses `boilerplate`, which can be installed via `go get`.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
@thetechnick How could I inject the new tool into the lint pipeline the smartest way? I could easily just add an `if command not found then download binary from github` statement into the verify-boilerplate.sh, but I don't know your preference towards these kind of things.

WDYT?

**Comment by nmiculinic** [comment]
```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index f4e50993..92822426 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -29,7 +29,7 @@ repos:
   - id: LICENSE
     name: LICENSE
     language: system
-    entry: bash ./hack/verify-boilerplate.sh
+    entry: boilerplate -exclude hack/docgen
     exclude: ".*"
     always_run: true
   - id: go-mod-tidy
```

Please apply this patch and it's good to go

**Comment by xrstf** [comment]
https://github.com/kubermatic/kubecarrier/pull/501 added boilerplate to the test image, but the lint job runs in the dev image.

**Comment by nmiculinic** [comment]
Adding it

https://github.com/kubermatic/kubecarrier/pull/513

**Pull request merged**
