### PR TITLE
Added protoc, helm & protoc-gen-* to test.dockerfile

### PR DESCRIPTION
**Pull request by nmiculinic**
**What this PR does / why we need it**:
It adds a few dependencies to the test.Dockerfile for new features introduced for the API Server PRs (#355  #366 ) 

```release-note
NONE
```

### CODE REVIEW

**Comment by jiachengxu** [comment]
The base branch of this PR should be the API server feature branch: `feature-api-server`

**Comment by nmiculinic** [comment]
retest

**Comment by nmiculinic** [comment]
/retest


prow is misbehaving...

**Pull request merged**
