### PR TITLE
Update dev image

### PR DESCRIPTION
**Pull request by aborilov**
**What this PR does / why we need it**:
`github.com/stretchr/testify` downloaded on each `make generate` run, so I've added it to dev image

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aborilov** [comment]
> if you check the lint job here: https://prow.loodse.com/view/gcs/prow-dev-data/pr-logs/pull/kubermatic_kubecarrier/423/pull-kubecarrier-lint/1260887740724023297, it is still using dev:v2, please push the dev images to quay.io and also change the .prow.yaml file to use v3.

done

**Comment by jiachengxu** [comment]
If you check the latest lint log: https://prow.loodse.com/view/gcs/prow-dev-data/pr-logs/pull/kubermatic_kubecarrier/423/pull-kubecarrier-lint/1260899568724217857
It is still executing `go: downloading github.com/stretchr/testify v1.4.0` during the running time, which means testify is not being used as a binary?

**Comment by thetechnick** [comment]
Within prow the GOPATH is always overrided to `/home/prow/go` instead of the image default, we need to either force the GOPATH back to `/go` in our Makefile or change the dev.Dockerfile to set the GOPATH to `/home/prow/go` by default - otherwise go will not find these dependencies.

**Pull request merged**
