### PR TITLE
Increase make generate performance on Mac by using delegated mount mode

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:
The current implementations of mounts on Linux provide a consistent view of a host directory tree inside a container: reads and writes performed either on the host or in the container are immediately reflected in the other environment, and file system events (inotify, FSEvents) are consistently propagated in both directions.
On Linux, these guarantees carry no overhead, since the underlying VFS is shared directly between host and container. However, on macOS (and other non-Linux platforms) there are significant overheads to guaranteeing perfect consistency.
This PR using `delegated` (the container’s view is authoritative (permit delays before updates on the container appear in the host)) to increase the performance of `make generate` on MacOS.
Ref: https://docs.docker.com/docker-for-mac/osxfs-caching/
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nmiculinic** [comment]
Does this have any drawbacks to linux?

**Comment by jiachengxu** [comment]
> Does this have any drawbacks to linux?

As far as I know, nope

**Pull request merged**
