### PR TITLE
increased APIServer limits

### PR DESCRIPTION
**Pull request by nmiculinic**
On my machine API server took on average 1000-2000ms to respond to every API request. A bit too much, isn't it? 

```release-note
NONE
```

### CODE REVIEW

**Comment by aborilov** [comment]
```
Running 10s test @ https://localhost:9443/v1/whoami
  6 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   113.27ms   93.53ms 494.39ms   63.38%
    Req/Sec    10.21      6.45    30.00     70.79%
  529 requests in 10.09s, 174.61KB read
Requests/sec:     52.41
Transfer/sec:     17.30KB
```
on my machine it takes only 113ms avg

**Comment by nmiculinic** [comment]
/retest

hmmmm....yeah, I kinda feel I'm overusing my laptop with 2 kind clusters ,slack, firefox, InteliJ... The memory gets full and I'm swapping :-/

**Comment by jiachengxu** [comment]
> ```
> Running 10s test @ https://localhost:9443/v1/whoami
>   6 threads and 10 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency   113.27ms   93.53ms 494.39ms   63.38%
>     Req/Sec    10.21      6.45    30.00     70.79%
>   529 requests in 10.09s, 174.61KB read
> Requests/sec:     52.41
> Transfer/sec:     17.30KB
> ```
> 
> on my machine it takes only 113ms avg

@aborilov , which tool did you use for testing? I would like also to have a try :)

**Comment by aborilov** [comment]
> > ```
> > Running 10s test @ https://localhost:9443/v1/whoami
> >   6 threads and 10 connections
> >   Thread Stats   Avg      Stdev     Max   +/- Stdev
> >     Latency   113.27ms   93.53ms 494.39ms   63.38%
> >     Req/Sec    10.21      6.45    30.00     70.79%
> >   529 requests in 10.09s, 174.61KB read
> > Requests/sec:     52.41
> > Transfer/sec:     17.30KB
> > ```
> > 
> > 
> > on my machine it takes only 113ms avg
> 
> @aborilov , which tool did you use for testing? I would like also to have a try :)

https://github.com/wg/wrk
`wrk -t 6 -c 10 https://localhost:9443/v1/whoami`

**Comment by nmiculinic** [comment]
What about API endpoint doing more work? 100ms....it's actually a lot for endpoint doing pretty much nothing.

**Comment by aborilov** [comment]
> What about API endpoint doing more work? 100ms....it's actually a lot for endpoint doing pretty much nothing.

we need to do such tests on real k8s cluster, not kind with kubeproxy.

**Comment by aborilov** [comment]
and yeah, 100ms too much for doing nothing

**Pull request merged**
