### PR TITLE
Replace sudo chown with --user flag in docker

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:
This PR replaces sudo chown with --user flag in docker.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jiachengxu** [comment]
@neven Can you please confirm if this works on Linux?

**Comment by nmiculinic** [comment]
/lgtm

works for me!

**Pull request merged**
