### PR TITLE
Fix the unknown phase when KubeCarrier is ready

### LINKED ISSUE #539: [Bug] KubeCarrier ready, but phase unknown
**Describe the bug**
KubeCarrier object conditions are True, but the phase is `Unkown`

```
apiVersion: operator.kubecarrier.io/v1alpha1
kind: KubeCarrier
metadata:
  creationTimestamp: "2020-08-04T11:51:32Z"
  generation: 1
  name: kubecarrier
  resourceVersion: "2327"
  selfLink: /apis/operator.kubecarrier.io/v1alpha1/kubecarriers/kubecarrier
  uid: 6b6f9929-acdc-4681-8b27-b09740a7d021
spec:
  api:
    authentication:
    - serviceAccount: {}
    - anonymous: {}
status:
  conditions:
  - lastTransitionTime: "2020-08-04T11:51:50Z"
    message: the deployment of KubeCarrier is ready
    reason: DeploymentReady
    status: "True"
    type: DeploymentReady
  - lastTransitionTime: "2020-08-04T11:51:50Z"
    message: the deployment of KubeCarrier and API Server are ready.
    reason: KubeCarrierReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-08-04T11:51:46Z"
    message: APIServer is ready
    reason: APIServerReady
    status: "True"
    type: APIServerReady
  observedGeneration: 1
  phase: Unknown
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kubernetes/Openshift Cluster**
- Version

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #539 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nmiculinic** [comment]
Was this code copy/pasted around a few times? Do we have similar problems in the codebase? 

(One big issue is this was written, not auto-generated)

**Comment by jiachengxu** [comment]
Created an issue in #541 to track bugs of Paused flag, will do a complete fix later

**Pull request closed without merging**
