### PR TITLE
Revert tower

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:
This PR reverts the following 2 PRs:
https://github.com/kubermatic/kubecarrier/pull/335
https://github.com/kubermatic/kubecarrier/pull/333
These changes regarding multi-region will be pushed to `feature/master-controller-manager` branch

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nmiculinic** [comment]
I mean sure.... @thetechnick ?

**Comment by thetechnick** [comment]
/lgtm
/hold
@jiachengxu Could you please put the code into a `feature/master-controller-manager` branch and open a WIP PR from the feature branch into master?

**Comment by jiachengxu** [comment]
> @jiachengxu Could you please put the code into a `feature/master-controller-manager` branch and open a WIP PR from the feature branch into master?

Sure, will do 👍
/unhold

**Pull request merged**
